#ifndef DINO_GRAPHICS_FRAMES_H
#define DINO_GRAPHICS_FRAMES_H

#define DINO_FRAME1_LINE00 "''''''''"
#define DINO_FRAME1_LINE01 "''''''''"
#define DINO_FRAME1_LINE02 "''''''''"
#define DINO_FRAME1_LINE03 "''''####"
#define DINO_FRAME1_LINE04 "''''#'##"
#define DINO_FRAME1_LINE05 "''''####"
#define DINO_FRAME1_LINE06 "''''##''"
#define DINO_FRAME1_LINE07 "'''###''"
#define DINO_FRAME1_LINE08 "#'#####'"
#define DINO_FRAME1_LINE09 "######''"
#define DINO_FRAME1_LINE10 "'#####''"
#define DINO_FRAME1_LINE11 "''####''"
#define DINO_FRAME1_LINE12 "'''#''''"
#define DINO_FRAME1_LINE13 "'''#''''"
#define DINO_FRAME1_LINE14 "''''''''"
#define DINO_FRAME1_LINE15 "''''''''"

#define DINO_FRAME2_LINE00 "''''''''"
#define DINO_FRAME2_LINE01 "''''''''"
#define DINO_FRAME2_LINE02 "''''''''"
#define DINO_FRAME2_LINE03 "''''####"
#define DINO_FRAME2_LINE04 "''''#'##"
#define DINO_FRAME2_LINE05 "''''####"
#define DINO_FRAME2_LINE06 "''''##''"
#define DINO_FRAME2_LINE07 "'''###''"
#define DINO_FRAME2_LINE08 "#'#####'"
#define DINO_FRAME2_LINE09 "######''"
#define DINO_FRAME2_LINE10 "'#####''"
#define DINO_FRAME2_LINE11 "''####''"
#define DINO_FRAME2_LINE12 "'''''#''"
#define DINO_FRAME2_LINE13 "'''''#'"
#define DINO_FRAME2_LINE14 "''''''''"
#define DINO_FRAME2_LINE15 "''''''''"


#define PLANE_FRAME01 "'''''''#"
#define PLANE_FRAME02 "'#######"
#define PLANE_FRAME03 "#'#'#'##"
#define PLANE_FRAME04 "n#######"
#define PLANE_FRAME05 "'''###''"
#define PLANE_FRAME06 "''''##''"
#define PLANE_FRAME07 "'''''##'"
#define PLANE_FRAME08 "''''''''"

#define HOUSE_FRAME01 "''''''''"
#define HOUSE_FRAME02 "'''##'''"
#define HOUSE_FRAME03 "''####''"
#define HOUSE_FRAME04 "'######'"
#define HOUSE_FRAME05 "########"
#define HOUSE_FRAME06 "'####'#'"
#define HOUSE_FRAME07 "'#''###'"
#define HOUSE_FRAME08 "'#''###'"


#define BIG_BUILDING01 "''''#'''"
#define BIG_BUILDING02 "''''#'''"
#define BIG_BUILDING03 "''''##''"
#define BIG_BUILDING04 "'######'"
#define BIG_BUILDING05 "########"
#define BIG_BUILDING06 "########"
#define BIG_BUILDING07 "#''##''#"
#define BIG_BUILDING08 "#''##''#"
#define BIG_BUILDING09 "#''##''#"
#define BIG_BUILDING010 "########"
#define BIG_BUILDING011 "########"
#define BIG_BUILDING012 "#''##''#"
#define BIG_BUILDING013 "#''##''#"
#define BIG_BUILDING014 "#''##''#"
#define BIG_BUILDING015 "########"
#define BIG_BUILDING016 "########"
#define BIG_BUILDING017 "#''##''#"
#define BIG_BUILDING018 "#''##''#"
#define BIG_BUILDING019 "#''##''#"
#define BIG_BUILDING020 "########"
#define BIG_BUILDING021 "########"
#define BIG_BUILDING022 "########"
#define BIG_BUILDING023 "###''###"
#define BIG_BUILDING024 "###''###"


#define MEDIUM_BUILDING01 "########"
#define MEDIUM_BUILDING02 "########"
#define MEDIUM_BUILDING03 "#''##''#"
#define MEDIUM_BUILDING04 "#''##''#"
#define MEDIUM_BUILDING05 "########"
#define MEDIUM_BUILDING06 "########"
#define MEDIUM_BUILDING07 "#''##''#"
#define MEDIUM_BUILDING08 "#''##''#"
#define MEDIUM_BUILDING09 "########"
#define MEDIUM_BUILDING10 "########"
#define MEDIUM_BUILDING11 "#''##''#"
#define MEDIUM_BUILDING11 "#''##''#"
#define MEDIUM_BUILDING12 "########"
#define MEDIUM_BUILDING13 "########"
#define MEDIUM_BUILDING14 "###''###"
#define MEDIUM_BUILDING15 "###''###"




#endif //DINO_GRAPHICS_FRAMES_H
